name: Python package

on:
  push:
    paths-ignore:
      - README.md
      - _changelogs/**
      - wiki/**
      - wiki_data/**
      - .gitignore
      - .github/**
  pull_request:
    types:
      - closed

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install Pillow matplotlib numpy pure-python-adb requests pyqt5
      - name: Test with pytest
        run: |
          pytest